### PR TITLE
Fixes configure usage

### PR DESCRIPTION
**Pull request by bfosberry**

### CODE REVIEW

**Comment by ngauthier** [comment]
please run `jet steps --tag=master`

**Comment by bfosberry** [comment]
Regardless of whether the build works, this fixes the broken usage of configure. We should either strip out the broken jet implementation, and work through all of this in a branch, or be happy to merge this in without the deploy piece passing

**Comment by ngauthier** [comment]
ok I added debug output, which yields this on a run:

```
***WARNING*** linux detected, --no-remove is recommended to be set to docker bug with linux https://github.com/docker/docker/issues/9665
{StepStarted=step_name:"shipscope_bin/xvfb-grunt-test"}
{BuildImageStarted=image_name:"codeship/shipscope" service_name:"shipscope"}
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}: Step 0 : FROM node:4.0
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> c9baaf3a0792
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}: Step 1 : MAINTAINER Codeship <dev@codeship.com>
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> Using cache
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> a57258adfb19
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}: Step 2 : RUN curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&   echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> Using cache
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> c57e3cc1b5fa
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}: Step 3 : RUN apt-get update && apt-get install -y   google-chrome-stable   unzip   xvfb
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> Using cache
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> 2e9a8cee9456
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}: Step 4 : WORKDIR /app
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> Using cache
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> 41fcadcd2cc1
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}: Step 5 : ADD package.json ./package.json
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> Using cache
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> b9130aafdb7f
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}: Step 6 : RUN npm install
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> Using cache
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> e26f447c88bf
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}: Step 7 : RUN npm install grunt --save-dev
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> Using cache
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> 7d783692adf5
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}: Step 8 : ADD . ./
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> Using cache
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}:  ---> 568bfd807d4e
{BuildImageStdout=image_name:"codeship/shipscope" service_name:"shipscope"}: Successfully built 568bfd807d4e
{BuildImageFinished=image_name:"codeship/shipscope" service_name:"shipscope"}
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: /app
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: total 80
-rw-rw-r--  1 root root  1421 Sep 15 12:33 CODE_OF_CONDUCT.md
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: -rw-rw-r--  1 root root  1579 Sep 15 12:33 CONTRIBUTING.md
-rw-rw-r--  1 root root   200 Sep 16 17:51 Dockerfile.deploy
-rw-rw-r--  1 root root  1906 Sep 15 14:16 Gruntfile.js
-rw-rw-r--  1 root root 11324 Sep 15 12:33 LICENSE
-rw-rw-r--  1 root root  1775 Sep 15 12:33 README.md
drwxrwxr-x  7 root root  4096 Sep 15 12:33 app
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: -rw-rw-r--  1 root root   252 Sep 16 14:11 aws-deployment.env.encrypted
drwxrwxr-x  2 root root  4096 Sep 16 17:45 bin
-rw-rw-r--  1 root root   294 Sep 16 17:45 codeship-services.yml
-rw-rw-r--  1 root root   168 Sep 16 17:43 codeship-steps.yml
-rw-rw-r--  1 root root    45 Sep 16 14:11 codeship.aes
-rw-rw-r--  1 root root  2317 Sep 15 14:29 karma.conf.js
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: drwxrwxr-x  2 root root  4096 Sep 15 12:33 mockship
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: drwxr-xr-x 21 root root  4096 Sep 16 17:48 node_modules
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: -rw-rw-r--  1 root root   871 Sep 15 14:35 package.json
drwxrwxr-x  4 root root  4096 Sep 15 12:33 test
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: drwxrwxr-x  2 root root  4096 Sep 15 12:33 webstore
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: Running "clean:0" (clean) task
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: >> 0 paths cleaned.
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: 
Running "clean:1" (clean) task
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: >> 0 paths cleaned.
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: Running "clean:2" (clean) task
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: >> 0 paths cleaned.
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}:
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: Running "uglify:shipscope" (uglify) task
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: >> 2 sourcemaps created.
>> 2 files created.
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: 
Running "karma:unit" (karma) task
                                                                                         Chrome 45.0.2454 (Linux 0.0.0): Executed 40 of 49 (skipped 9) SUCCESS (0.093 secs / 0.018 secs)
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: 
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: =============================== Coverage summary ===============================
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: Statements   : 51.33% ( 116/226 )
Branches     : 51.16% ( 44/86 )
Functions    : 51.47% ( 35/68 )
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: Lines        : 51.8% ( 115/222 )
================================================================================
{ContainerRunStdout=step_name:"shipscope_bin/xvfb-grunt-test" service_name:"shipscope"}: 
Done, without errors.
{StepFinished=step_name:"shipscope_bin/xvfb-grunt-test" type:STEP_FINISHED_TYPE_SUCCESS}
{StepStarted=step_name:"shipscope_bin/deploy"}
{BuildImageStarted=image_name:"codeship/shipscope" service_name:"shipscope"}
{BuildImageFinished=image_name:"codeship/shipscope" service_name:"shipscope"}
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: /checkout_volume
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: total 184
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: -rw-rw-r-- 1 1000 1000  1421 Sep 15 12:33 CODE_OF_CONDUCT.md
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: -rw-rw-r-- 1 1000 1000  1579 Sep 15 12:33 CONTRIBUTING.md
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: -rw-rw-r-- 1 1000 1000   433 Sep 16 17:48 Dockerfile
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: -rw-rw-r-- 1 1000 1000   200 Sep 16 17:51 Dockerfile.deploy
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: -rw-rw-r-- 1 1000 1000  1906 Sep 15 14:16 Gruntfile.js
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: -rw-rw-r-- 1 1000 1000 11324 Sep 15 12:33 LICENSE
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: -rw-rw-r-- 1 1000 1000  1775 Sep 15 12:33 README.md
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: drwxrwxr-x 7 1000 1000  4096 Sep 15 12:33 app
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: -rw-rw-r-- 1 1000 1000   252 Sep 16 14:11 aws-deployment.env.encrypted
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: drwxrwxr-x 2 1000 1000  4096 Sep 16 17:45 bin
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: -rw-rw-r-- 1 1000 1000   294 Sep 16 17:45 codeship-services.yml
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: -rw-rw-r-- 1 1000 1000   168 Sep 16 17:43 codeship-steps.yml
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: -rw-rw-r-- 1 1000 1000    45 Sep 16 14:11 codeship.aes
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: -rw-rw-r-- 1 1000 1000  2317 Sep 15 14:29 karma.conf.js
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: drwxrwxr-x 2 1000 1000  4096 Sep 15 12:33 mockship
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: -rw-rw-r-- 1 1000 1000   871 Sep 15 14:35 package.json
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: drwxrwxr-x 4 1000 1000  4096 Sep 15 12:33 test
{ContainerRunStdout=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: drwxrwxr-x 2 1000 1000  4096 Sep 15 12:33 webstore
{ContainerRunStderr=step_name:"shipscope_bin/deploy" service_name:"shipscope"}: bin/build: line 5: node_modules/.bin/grunt: No such file or directory
{ContainerRunError=step_name:"shipscope_bin/deploy" service_name:"shipscope" exit_code:1}
{StepFinished=step_name:"shipscope_bin/deploy" type:STEP_FINISHED_TYPE_ERROR}
```

**Comment by ngauthier** [comment]
notice that when we run the tests, there's a `node_modules` folder and pwd is `/app`. But when we are running the configure build there's no `node_modules` and pwd is `/checkout_volume`.

So, the configure section doesn't contain the contents of the built shipscope service, it just contains the original checkout.

So we don't have grunt and so we can't build the artifact.

**Comment by bfosberry** [comment]
Closing, we should eventually move this to using volumes

**Pull request closed without merging**
